version: 0.2

phases:
    install:
        commands:
            - curl -L https://github.com/docker/compose/releases/download/1.12.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
            - docker-compose --version
            - docker-compose pull

    build:
        commands:
            - ant test

artifacts:
    type: zip
    files:
        - '.'