version: 0.2

phases:
    install:
        commands:
            - apt-get install docker
            - curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
            - docker-compose --version
            - composer --version
            - composer global require phing/phing

    build:
        commands:
            - phing install
            - phing test -verbose

artifacts:
    type: zip
    files:
        - "**/*"